# Đáp án chi tiết - Tur3: Các thư viện quan trọng trong KHDL của Python

Notebook này cung cấp **đáp án đầy đủ** cho các bài thực hành NumPy và Pandas.
Mỗi bài đều có:
- Code hoàn chỉnh
- Giải thích ngắn gọn, dễ hiểu
- Kết quả trung gian quan trọng để tự kiểm tra

# Phần 1: Thư viện NumPy

## Bài 1.1 - Tạo ma trận, đổi kiểu dữ liệu, broadcasting

In [1]:
import numpy as np

# 1) Tạo ma trận A
A = np.array([
    [5.1, 8.7, 3.3],
    [4.4, 0.9, 9.5],
    [6.2, 7.5, 1.8]
])
print("A:\n", A)

# 2) Đổi kiểu sang số nguyên -> B
B = A.astype(int)
print("\nB (int):\n", B)
print("dtype của B:", B.dtype)

# 3) Cộng với vector float64 u (broadcast theo hàng)
u = np.array([0.5, 1.5, 2.5], dtype=np.float64)
C = B + u
print("\nC = B + u:\n", C)
print("dtype của C:", C.dtype)

# 4) Cộng với vector int32 v
v = np.array([10, 20, 30], dtype=np.int32)
D = B + v
print("\nD = B + v:\n", D)
print("dtype của D:", D.dtype)

print("\nGiải thích:")
print("- astype(int) cắt phần thập phân để tạo B kiểu int.")
print("- Khi cộng ma trận 3x3 với vector 3 phần tử, NumPy broadcasting theo từng cột.")
print("- C có dtype float vì cộng với vector float64.")

A:
 [[5.1 8.7 3.3]
 [4.4 0.9 9.5]
 [6.2 7.5 1.8]]

B (int):
 [[5 8 3]
 [4 0 9]
 [6 7 1]]
dtype của B: int64

C = B + u:
 [[ 5.5  9.5  5.5]
 [ 4.5  1.5 11.5]
 [ 6.5  8.5  3.5]]
dtype của C: float64

D = B + v:
 [[15 28 33]
 [14 20 39]
 [16 27 31]]
dtype của D: int64

Giải thích:
- astype(int) cắt phần thập phân để tạo B kiểu int.
- Khi cộng ma trận 3x3 với vector 3 phần tử, NumPy broadcasting theo từng cột.
- C có dtype float vì cộng với vector float64.


## Bài 1.2 - Slicing, fancy indexing, boolean indexing

In [2]:
import numpy as np

# 1) Tạo ma trận M 6x6 chứa số từ 0 đến 35
M = np.arange(36).reshape(6, 6)
print("M:\n", M)

# 2) Trích xuất vùng trung tâm 4x4 (hàng 1:5, cột 1:5)
P = M[1:5, 1:5]
print("\nP (vùng trung tâm 4x4):\n", P)

# 3) Chọn các hàng 0 và 3 của P
selected_rows = P[[0, 3], :]
print("\nHàng 0 và 3 của P:\n", selected_rows)

# 4) Gán -99 cho cột 1 và 2 của M
M[:, [1, 2]] = -99
print("\nM sau khi gán -99 vào cột 1 và 2:\n", M)

# 5) Lấy các cột lẻ (1,3,5) rồi lọc giá trị > 20
odd_cols = M[:, [1, 3, 5]]
greater_than_20 = odd_cols[odd_cols > 20]
print("\nCác cột lẻ (1,3,5):\n", odd_cols)
print("\nGiá trị > 20 trong các cột lẻ:", greater_than_20)

print("\nGiải thích:")
print("- [1:5] lấy từ chỉ số 1 đến 4.")
print("- [[0,3], :] là fancy indexing để chọn nhiều hàng không liên tiếp.")
print("- Boolean indexing giúp lọc nhanh theo điều kiện > 20.")

M:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

P (vùng trung tâm 4x4):
 [[ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]

Hàng 0 và 3 của P:
 [[ 7  8  9 10]
 [25 26 27 28]]

M sau khi gán -99 vào cột 1 và 2:
 [[  0 -99 -99   3   4   5]
 [  6 -99 -99   9  10  11]
 [ 12 -99 -99  15  16  17]
 [ 18 -99 -99  21  22  23]
 [ 24 -99 -99  27  28  29]
 [ 30 -99 -99  33  34  35]]

Các cột lẻ (1,3,5):
 [[-99   3   5]
 [-99   9  11]
 [-99  15  17]
 [-99  21  23]
 [-99  27  29]
 [-99  33  35]]

Giá trị > 20 trong các cột lẻ: [21 23 27 29 33 35]

Giải thích:
- [1:5] lấy từ chỉ số 1 đến 4.
- [[0,3], :] là fancy indexing để chọn nhiều hàng không liên tiếp.
- Boolean indexing giúp lọc nhanh theo điều kiện > 20.


## Bài 1.3 - Ma trận ngẫu nhiên, chuyển vị, thống kê theo hàng

In [3]:
import numpy as np

np.random.seed(42)  # Đặt seed để kết quả có thể lặp lại

# 1) Ma trận ngẫu nhiên 4x5 trong [10, 100)
data = np.random.randint(10, 100, size=(4, 5))
print("data:\n", data)

# 2) Chuyển vị
data_T = data.T
print("\ndata.T:\n", data_T)

# 3) Max và min theo từng hàng (axis=1)
row_max = data.max(axis=1)
row_min = data.min(axis=1)
print("\nMax từng hàng:", row_max)
print("Min từng hàng:", row_min)

# 4) Chỉ số cột có giá trị lớn nhất ở mỗi hàng
argmax_col = data.argmax(axis=1)
print("\nChỉ số cột max mỗi hàng:", argmax_col)

print("\nGiải thích:")
print("- axis=1 nghĩa là tính theo từng hàng.")
print("- argmax(axis=1) trả về vị trí cột của phần tử lớn nhất trong mỗi hàng.")

data:
 [[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]
 [97 39 47 11 73]]

data.T:
 [[61 92 33 97]
 [24 96 12 39]
 [81 84 31 47]
 [70 84 62 11]
 [30 97 11 73]]

Max từng hàng: [81 97 62 97]
Min từng hàng: [24 84 11 11]

Chỉ số cột max mỗi hàng: [2 4 3 0]

Giải thích:
- axis=1 nghĩa là tính theo từng hàng.
- argmax(axis=1) trả về vị trí cột của phần tử lớn nhất trong mỗi hàng.


## Bài 1.4 - Ứng dụng ma trận chi phí trong sản xuất

In [4]:
import numpy as np

# 1) Ma trận chi phí theo sản phẩm (A,B,C) x loại chi phí (NVL, nhân công, vận hành)
costs = np.array([
    [10, 5, 2],
    [12, 7, 3],
    [9, 4, 2.5]
])
print("Ma trận costs:\n", costs)

# 2) Vector số lượng sản xuất
production_volume = np.array([1000, 500, 1500])
print("\nSố lượng sản xuất:", production_volume)

# 3) Tổng chi phí cho từng loại chi phí
# Nhân từng hàng với sản lượng tương ứng rồi cộng theo trục sản phẩm
total_cost_by_type = (costs * production_volume.reshape(-1, 1)).sum(axis=0)
print("\nTổng chi phí theo loại [NVL, Nhân công, Vận hành]:", total_cost_by_type)

# 4) Tổng chi phí cho từng sản phẩm trên 1 đơn vị sản phẩm
unit_cost_per_product = costs.sum(axis=1)
print("\nTổng chi phí/đơn vị theo sản phẩm [A,B,C]:", unit_cost_per_product)

print("\nGiải thích:")
print("- reshape(-1,1) để production_volume có dạng cột và broadcast đúng với costs.")
print("- sum(axis=0): cộng theo chiều sản phẩm để ra tổng theo từng loại chi phí.")

Ma trận costs:
 [[10.   5.   2. ]
 [12.   7.   3. ]
 [ 9.   4.   2.5]]

Số lượng sản xuất: [1000  500 1500]

Tổng chi phí theo loại [NVL, Nhân công, Vận hành]: [29500. 14500.  7250.]

Tổng chi phí/đơn vị theo sản phẩm [A,B,C]: [17.  22.  15.5]

Giải thích:
- reshape(-1,1) để production_volume có dạng cột và broadcast đúng với costs.
- sum(axis=0): cộng theo chiều sản phẩm để ra tổng theo từng loại chi phí.


## Bài 1.5 - Hàm Sigmoid bằng NumPy

In [5]:
import numpy as np

# 1) Tạo mảng x từ -3 đến 3, bước 0.5
x = np.arange(-3, 3.5, 0.5)
print("x:", np.round(x, 2))

# 2) Tính Sigmoid: 1 / (1 + exp(-x))
sigmoid = 1 / (1 + np.exp(-x))
print("Sigmoid(x):", np.round(sigmoid, 4))

print("\nGiải thích:")
print("- Với x âm lớn, sigmoid gần 0; với x dương lớn, sigmoid gần 1.")
print("- Đây là hàm phổ biến trong học máy để nén giá trị về khoảng (0,1).")

x: [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
Sigmoid(x): [0.0474 0.0759 0.1192 0.1824 0.2689 0.3775 0.5    0.6225 0.7311 0.8176
 0.8808 0.9241 0.9526]

Giải thích:
- Với x âm lớn, sigmoid gần 0; với x dương lớn, sigmoid gần 1.
- Đây là hàm phổ biến trong học máy để nén giá trị về khoảng (0,1).


## Bài 1.6 - Định thức, khả nghịch, nghiệm hệ phương trình

In [6]:
import numpy as np

# Chọn một ma trận khả nghịch (det != 0)
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 0]
], dtype=float)
b = np.array([4, 5, 6], dtype=float)

print("A:\n", A)
print("b:", b)

# 2) Định thức và kiểm tra khả nghịch
det_A = np.linalg.det(A)
print("\nĐịnh thức det(A) =", det_A)
if abs(det_A) > 1e-10:
    print("A khả nghịch")
else:
    print("A không khả nghịch")

# 3) Ma trận nghịch đảo
A_inv = np.linalg.inv(A)
print("\nA^-1:\n", A_inv)

# 4) Nghiệm x = A^-1 b
x = A_inv @ b
print("\nNghiệm x:", x)

# 5) Kiểm tra Ax có bằng b không
check_b = A @ x
print("\nA @ x =", check_b)
print("So sánh với b:", np.allclose(check_b, b))

print("\nGiải thích:")
print("- Nếu det(A)=0 thì không thể tính nghịch đảo.")
print("- np.allclose dùng để kiểm tra gần bằng do sai số số học dấu chấm động.")

A:
 [[2. 1. 1.]
 [1. 3. 2.]
 [1. 0. 0.]]
b: [4. 5. 6.]

Định thức det(A) = -1.0
A khả nghịch

A^-1:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]

Nghiệm x: [  6.  15. -23.]

A @ x = [4. 5. 6.]
So sánh với b: True

Giải thích:
- Nếu det(A)=0 thì không thể tính nghịch đảo.
- np.allclose dùng để kiểm tra gần bằng do sai số số học dấu chấm động.


# Phần 2: Thư viện Pandas

## Bài 2.1 - Series từ dictionary và vector hóa

In [7]:
import pandas as pd

# 1) Tạo Series
population_dict = {
    "Hanoi": 8.5,
    "HCMC": 9.3,
    "Danang": 1.2,
    "Haiphong": 2.1
}
city_pop = pd.Series(population_dict, name="Dân số (triệu)")
print("Dân số các thành phố (triệu người):")
print(city_pop)

# 2) Trích xuất dữ liệu
print("\nDân số Hà Nội:", city_pop["Hanoi"], "triệu")
print("Dân số Đà Nẵng:", city_pop["Danang"], "triệu")

# 3) Vector hóa: đổi từ triệu người sang người
city_pop_people = (city_pop * 1_000_000).astype(int)
print("\nDân số quy đổi sang người:")
print(city_pop_people)

print("\nGiải thích: Nhân trực tiếp cả Series là phép toán vector hóa, không cần vòng lặp.")

Dân số các thành phố (triệu người):
Hanoi       8.5
HCMC        9.3
Danang      1.2
Haiphong    2.1
Name: Dân số (triệu), dtype: float64

Dân số Hà Nội: 8.5 triệu
Dân số Đà Nẵng: 1.2 triệu

Dân số quy đổi sang người:
Hanoi       8500000
HCMC        9300000
Danang      1200000
Haiphong    2100000
Name: Dân số (triệu), dtype: int64

Giải thích: Nhân trực tiếp cả Series là phép toán vector hóa, không cần vòng lặp.


## Bài 2.2 - DataFrame, thêm cột theo điều kiện, xóa cột

In [8]:
import pandas as pd
import numpy as np

# 1) Tạo DataFrame
sales_data = {
    "nhan_vien": ["An", "Binh", "Chi", "Dung"],
    "khu_vuc": ["Bắc", "Nam", "Trung", "Bắc"],
    "doanh_so": [120, 250, 180, 90]
}
sales_df = pd.DataFrame(sales_data)
print("DataFrame ban đầu:\n", sales_df)

# 2) Cột thuong: True nếu doanh_so > 100
sales_df["thuong"] = sales_df["doanh_so"] > 100

# 3) Cột tien_thuong: 10% doanh số nếu được thưởng, ngược lại 0
sales_df["tien_thuong"] = np.where(sales_df["thuong"], sales_df["doanh_so"] * 0.1, 0)

# 4) Xóa cột khu_vuc
sales_df = sales_df.drop(columns=["khu_vuc"])

print("\nDataFrame sau khi xử lý:\n", sales_df)

print("\nGiải thích:")
print("- np.where giúp tạo cột theo điều kiện nhanh và rõ ràng.")
print("- drop(columns=[...]) dùng để xóa cột không còn cần thiết.")

DataFrame ban đầu:
   nhan_vien khu_vuc  doanh_so
0        An     Bắc       120
1      Binh     Nam       250
2       Chi   Trung       180
3      Dung     Bắc        90

DataFrame sau khi xử lý:
   nhan_vien  doanh_so  thuong  tien_thuong
0        An       120    True         12.0
1      Binh       250    True         25.0
2       Chi       180    True         18.0
3      Dung        90   False          0.0

Giải thích:
- np.where giúp tạo cột theo điều kiện nhanh và rõ ràng.
- drop(columns=[...]) dùng để xóa cột không còn cần thiết.


## Bài 2.3 - Truy cập dữ liệu với loc và iloc

In [9]:
import pandas as pd
import numpy as np

# 1) Tạo DataFrame 4x4 từ 0 đến 15
df = pd.DataFrame(
    np.arange(16).reshape(4, 4),
    index=["A", "B", "C", "D"],
    columns=["W", "X", "Y", "Z"]
)
print("DataFrame gốc:\n", df)

# 2) loc: hàng A,C và cột W,Y
loc_selection = df.loc[["A", "C"], ["W", "Y"]]
print("\nLấy bằng loc:\n", loc_selection)

# 3) iloc: 2 hàng cuối (2,3) và 2 cột đầu (0,1)
iloc_selection = df.iloc[2:4, 0:2]
print("\nLấy bằng iloc:\n", iloc_selection)

# 4) Giá trị tại hàng B, cột Z
value_BZ = df.loc["B", "Z"]
print("\nGiá trị tại [B, Z]:", value_BZ)

print("\nGiải thích: loc theo nhãn, iloc theo vị trí số nguyên.")

DataFrame gốc:
     W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

Lấy bằng loc:
    W   Y
A  0   2
C  8  10

Lấy bằng iloc:
     W   X
C   8   9
D  12  13

Giá trị tại [B, Z]: 7

Giải thích: loc theo nhãn, iloc theo vị trí số nguyên.


## Bài 2.4 - Reindex và điền giá trị thiếu

In [10]:
import pandas as pd

# 1) Tạo Series ban đầu
product_stock = pd.Series([10, 50, 30], index=[0, 3, 5])
print("Series ban đầu:\n", product_stock)

# 2) Reindex từ 0 đến 5
reindexed = product_stock.reindex(range(6))
print("\nSeries sau reindex (có NaN):\n", reindexed)

# 3) Reindex + ffill
reindexed_ffill = product_stock.reindex(range(6), method="ffill")
print("\nSeries sau reindex + ffill:\n", reindexed_ffill)

print("\nGiải thích:")
print("- reindex thêm các chỉ số mới, vị trí chưa có dữ liệu sẽ là NaN.")
print("- ffill điền giá trị gần nhất phía trước.")

Series ban đầu:
 0    10
3    50
5    30
dtype: int64

Series sau reindex (có NaN):
 0    10.0
1     NaN
2     NaN
3    50.0
4     NaN
5    30.0
dtype: float64

Series sau reindex + ffill:
 0    10
1    10
2    10
3    50
4    50
5    30
dtype: int64

Giải thích:
- reindex thêm các chỉ số mới, vị trí chưa có dữ liệu sẽ là NaN.
- ffill điền giá trị gần nhất phía trước.


## Bài 2.5 - Sắp xếp, tính tổng điểm, thống kê mô tả

In [11]:
import pandas as pd

# 1) Tạo bảng điểm
scores_data = {
    "Toan": [7, 5, 9, 8],
    "Ly": [8, 9, 6, 7],
    "Hoa": [6, 8, 9, 5]
}
student_scores = pd.DataFrame(scores_data, index=["Hùng", "Lan", "Minh", "An"])
print("Bảng điểm ban đầu:\n", student_scores)

# 2) Sắp xếp theo Toán giảm dần
sorted_scores = student_scores.sort_values(by="Toan", ascending=False)
print("\nBảng điểm sau khi sắp xếp theo Toán giảm dần:\n", sorted_scores)

# 3) Thêm cột tổng điểm
student_scores["Tong_diem"] = student_scores[["Toan", "Ly", "Hoa"]].sum(axis=1)
print("\nBảng điểm có cột tổng điểm:\n", student_scores)

# 4) Thống kê mô tả
desc = student_scores[["Toan", "Ly", "Hoa"]].describe()
print("\nThống kê mô tả:\n", desc)

print("\nGiải thích: describe() cho các thống kê quan trọng như mean, std, min, max, tứ phân vị.")

Bảng điểm ban đầu:
       Toan  Ly  Hoa
Hùng     7   8    6
Lan      5   9    8
Minh     9   6    9
An       8   7    5

Bảng điểm sau khi sắp xếp theo Toán giảm dần:
       Toan  Ly  Hoa
Minh     9   6    9
An       8   7    5
Hùng     7   8    6
Lan      5   9    8

Bảng điểm có cột tổng điểm:
       Toan  Ly  Hoa  Tong_diem
Hùng     7   8    6         21
Lan      5   9    8         22
Minh     9   6    9         24
An       8   7    5         20

Thống kê mô tả:
            Toan        Ly       Hoa
count  4.000000  4.000000  4.000000
mean   7.250000  7.500000  7.000000
std    1.707825  1.290994  1.825742
min    5.000000  6.000000  5.000000
25%    6.500000  6.750000  5.750000
50%    7.500000  7.500000  7.000000
75%    8.250000  8.250000  8.250000
max    9.000000  9.000000  9.000000

Giải thích: describe() cho các thống kê quan trọng như mean, std, min, max, tứ phân vị.


## Bài 2.6 - Đọc file CSV, xử lý thiếu dữ liệu, tạo cột mới, lọc dữ liệu

In [12]:
# Tải dữ liệu nếu chưa có file transactions.csv
# Chạy cell này trên Colab/Jupyter để tải file về thư mục làm việc.
import os
import subprocess
import sys

file_id = "1Nty62dcwCcSbXWLK6vXUzUoU8s2Qy7j9"
if not os.path.exists("transactions.csv"):
    try:
        import gdown  # noqa: F401
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "gdown"])
    subprocess.check_call([sys.executable, "-m", "gdown", file_id, "-O", "transactions.csv"])

print("Tệp transactions.csv đã sẵn sàng.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [gdown]
Tệp transactions.csv đã sẵn sàng.


Downloading...
From: https://drive.google.com/uc?id=1Nty62dcwCcSbXWLK6vXUzUoU8s2Qy7j9
To: /Users/nguyennghia/PROJECT/DS_BUSSINESS/notebook/transactions.csv
100%|█████████████████████████████████████████| 318/318 [00:00<00:00, 1.15MB/s]


In [13]:
import pandas as pd

# 1) Đọc file CSV
df = pd.read_csv("transactions.csv")

# 2) Hiển thị thông tin cơ bản
print("5 dòng đầu tiên:")
print(df.head())
print("\nThông tin DataFrame:")
print(df.info())

# 3) Điền giá trị thiếu của cột SoLuong bằng 1
df["SoLuong"].fillna(1, inplace=True)

# 4) Tạo cột ThanhTien = DonGia * SoLuong
df["ThanhTien"] = df["DonGia"] * df["SoLuong"]

# 5) Lọc giao dịch nhóm hàng Điện tử
dien_tu_df = df[df["NhomHang"] == "Điện tử"]
print("\nGiao dịch nhóm hàng Điện tử:")
print(dien_tu_df)

print("\nGiải thích:")
print("- fillna(1) đảm bảo giao dịch thiếu số lượng vẫn tính được thành tiền.")
print("- Tạo cột mới bằng phép nhân giữa hai cột số là thao tác vector hóa trong Pandas.")
print("- Điều kiện lọc df[df['NhomHang'] == 'Điện tử'] giữ lại đúng nhóm cần phân tích.")

5 dòng đầu tiên:
    MaGD    SanPham    NhomHang  DonGia  SoLuong      NgayGD
0  TX001   Laptop A     Điện tử    25.0      2.0  2025-07-20
1  TX002   Bàn phím    Phụ kiện     1.2      5.0  2025-07-20
2  TX003  T-shirt B  Thời trang     0.5     10.0  2025-07-21
3  TX004   Màn hình     Điện tử     8.0      NaN  2025-07-21
4  TX005      Chuột    Phụ kiện     0.8      8.0  2025-07-22

Thông tin DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   MaGD      6 non-null      object 
 1   SanPham   6 non-null      object 
 2   NhomHang  6 non-null      object 
 3   DonGia    6 non-null      float64
 4   SoLuong   5 non-null      float64
 5   NgayGD    6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 420.0+ bytes
None

Giao dịch nhóm hàng Điện tử:
    MaGD   SanPham NhomHang  DonGia  SoLuong      NgayGD  ThanhTien
0  TX001  Laptop A  Điệ

/var/folders/8x/cphm0p8j0h16x_zm6w8f2nww0000gn/T/ipykernel_93755/1840153263.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["SoLuong"].fillna(1, inplace=True)


## Gợi ý tự học thêm

- Thử thay đổi dữ liệu đầu vào để xem kết quả thay đổi như thế nào.
- Với mỗi bài, hãy kiểm tra lại `dtype`, `shape`, và ý nghĩa kinh doanh của kết quả.
- Ưu tiên viết code theo hướng vector hóa (NumPy/Pandas) thay vì vòng lặp khi xử lý dữ liệu bảng.